version: '3.8'

services:
  db:
    image: postgres:14
    container_name: ${DB_HOST}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./database/scripts:/scripts
      - ./database/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    networks:
      - database

  soccer-bet-api:
    container_name: soccer-bet-api
    build:
      context: .
      target: dev
    env_file:
      - .env
    volumes:
      - .:/app:rw,delegated
    ports:
      - 8000:${API_PORT}
      - 2345:2345
    networks:
      - database
    depends_on:
      - db

networks:
  database:
    driver: bridge
