version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./db/scripts:/scripts
      - ./db/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${DB_PORT}:5432
    networks:
      - database

  soccer-bet-api:
    container_name: soccer-bet-api
    build:
      context: .
      target: dev
    environment:
      - API_PORT=${API_PORT}
    volumes:
    - .:/app:rw,delegated
    ports:
    - 8000:${API_PORT}
    - 2345:2345
    networks:
      - database
    depends_on:
      - db

networks:
  database:
    driver: bridge
