version: '3.8'
services:
  soccer-bet-api:
    container_name: soccer-bet-api
    build:
      context: .
      target: dev
    environment:
      - API_PORT=${API_PORT}
    volumes:
    - .:/app:rw,delegated
    ports:
    - 8000:${API_PORT}
    - 2345:2345
    networks:
      - database

networks:
  database:
    driver: bridge
